services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: .
            dockerfile: ./apps/nginx/Dockerfile
        ports:
            - 48273:48273
        networks:
            - app_network
        depends_on:
            - web

    web:
        container_name: web
        restart: always
        build:
            context: .
            dockerfile: ./apps/web/Dockerfile
        expose:
            - 5173
        networks:
            - app_network
        depends_on:
            - api

    api:
        container_name: api
        restart: always
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
        expose:
            - 3000
        networks:
            - app_network

networks:
    app_network:
